DEBUG: True
WANDB: True
WANDB_ENTITY: beyazit-y-berkeley-eecs
WANDB_PROJECT: rad-marl-jax
MAX_EP_LEN: 200
LAYOUT: |
    [ # ][ # ][ # ][ # ][ # ][ # ][ # ][ # ][ # ][ # ][ # ][ # ]
    [ # ][   ][   ][   ][   ][   ][   ][#,a][ 0 ][   ][ 1 ][ # ]
    [ # ][   ][   ][ b ][ b ][ b ][   ][#,a][   ][ 4 ][   ][ # ]
    [ # ][   ][   ][ b ][ b ][ b ][   ][#,a][ 3 ][   ][ 2 ][ # ]
    [ # ][   ][   ][ b ][ b ][ b ][   ][#,a][#,a][#,a][#,a][ # ]
    [ # ][ A ][   ][   ][   ][   ][   ][   ][   ][   ][   ][ # ]
    [ # ][ B ][   ][   ][   ][   ][   ][   ][   ][   ][   ][ # ]
    [ # ][   ][   ][ a ][ a ][ a ][   ][#,b][#,b][#,b][#,b][ # ]
    [ # ][   ][   ][ a ][ a ][ a ][   ][#,b][ 5 ][   ][ 6 ][ # ]
    [ # ][   ][   ][ a ][ a ][ a ][   ][#,b][   ][ 9 ][   ][ # ]
    [ # ][   ][   ][   ][   ][   ][   ][#,b][ 8 ][   ][ 7 ][ # ]
    [ # ][ # ][ # ][ # ][ # ][ # ][ # ][ # ][ # ][ # ][ # ][ # ]
DFA_SAMPLER: Reach
DFA_MAX_SIZE: 4
DFA_SIZE_P: null
DFA_PROB_STUTTER: 1
RHO_INIT: 0.5
RHO_DECAY_COEF: 1.0
RHO_TURNOFF_VAL: 0.0
MAX_REWARD: 2.0
ENCODER_DIM: 32
ENCODER_FILE_PREFIX: encoder_storage/encoder_rad_dim_32_max_size_10_n_tokens_10_params
SAVE_FILE_PREFIX: example_storage/example_policy_params
LOG_FILE_PREFIX: example_storage/log
# PPO PARAMS
LR: 0.00004
NUM_ENVS: 64
NUM_STEPS: 512
TOTAL_TIMESTEPS: 50_000_000
UPDATE_EPOCHS: 4
NUM_MINIBATCHES: 16
GAMMA: 0.99
GAE_LAMBDA: 0.95
CLIP_EPS: 0.2
ENT_COEF: 0.01
VF_COEF: 0.5
MAX_GRAD_NORM: 0.5
LR_ANNEAL_LINEAR: True
# LR_ANNEAL_EXP: True
# EXP_DECAY_RATE: 0.001
# LR_ANNEAL_COS: True
# LR_ANNEAL_WARMUP: True
# LR_ANNEAL_WARMUP_PARAM: 0.01
